version: '3'
services: 
  gateway-api:
    build:
      dockerfile: Dockerfile
      context: ./gateway-api/
    volumes: 
      - ./gateway-api/:/go/src/github.com/Mrcampbell/pgo2/gateway-api
    ports:
      - "8081:8081"
  pokemon-service:
    build:
      dockerfile: Dockerfile
      context: ./pokemon-service
    volumes: 
      - ./pokemon-service/:/go/src/github.com/Mrcampbell/pgo2/pokemon-service
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon
      TZ: America/Denver