// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pokemon/breedmove.proto

package pokemon

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LearnMethod int32

const (
	LearnMethod_LEARN_METHOD_UNKNOWN    LearnMethod = 0
	LearnMethod_LEVEL_UP                LearnMethod = 1
	LearnMethod_EGG                     LearnMethod = 2
	LearnMethod_TUTOR                   LearnMethod = 3
	LearnMethod_MACHINE                 LearnMethod = 4
	LearnMethod_STADIUM_SURFING_PIKACHU LearnMethod = 5
	LearnMethod_LIGHT_BALL_EGG          LearnMethod = 6
	LearnMethod_COLOSSEUM_PURIFICATION  LearnMethod = 7
	LearnMethod_XD_SHADOW               LearnMethod = 8
	LearnMethod_XD_PURIFICATION         LearnMethod = 9
	LearnMethod_FORM_CHANGE             LearnMethod = 10
)

var LearnMethod_name = map[int32]string{
	0:  "LEARN_METHOD_UNKNOWN",
	1:  "LEVEL_UP",
	2:  "EGG",
	3:  "TUTOR",
	4:  "MACHINE",
	5:  "STADIUM_SURFING_PIKACHU",
	6:  "LIGHT_BALL_EGG",
	7:  "COLOSSEUM_PURIFICATION",
	8:  "XD_SHADOW",
	9:  "XD_PURIFICATION",
	10: "FORM_CHANGE",
}

var LearnMethod_value = map[string]int32{
	"LEARN_METHOD_UNKNOWN":    0,
	"LEVEL_UP":                1,
	"EGG":                     2,
	"TUTOR":                   3,
	"MACHINE":                 4,
	"STADIUM_SURFING_PIKACHU": 5,
	"LIGHT_BALL_EGG":          6,
	"COLOSSEUM_PURIFICATION":  7,
	"XD_SHADOW":               8,
	"XD_PURIFICATION":         9,
	"FORM_CHANGE":             10,
}

func (x LearnMethod) String() string {
	return proto.EnumName(LearnMethod_name, int32(x))
}

func (LearnMethod) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_239b4783ea3a6a28, []int{0}
}

type GetMovesForBreedRequest struct {
	BreedId              string       `protobuf:"bytes,1,opt,name=breed_id,json=breedId,proto3" json:"breed_id,omitempty"`
	VersionGroupId       VersionGroup `protobuf:"varint,2,opt,name=version_group_id,json=versionGroupId,proto3,enum=pokemon.VersionGroup" json:"version_group_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMovesForBreedRequest) Reset()         { *m = GetMovesForBreedRequest{} }
func (m *GetMovesForBreedRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovesForBreedRequest) ProtoMessage()    {}
func (*GetMovesForBreedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_239b4783ea3a6a28, []int{0}
}

func (m *GetMovesForBreedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovesForBreedRequest.Unmarshal(m, b)
}
func (m *GetMovesForBreedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovesForBreedRequest.Marshal(b, m, deterministic)
}
func (m *GetMovesForBreedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovesForBreedRequest.Merge(m, src)
}
func (m *GetMovesForBreedRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovesForBreedRequest.Size(m)
}
func (m *GetMovesForBreedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovesForBreedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovesForBreedRequest proto.InternalMessageInfo

func (m *GetMovesForBreedRequest) GetBreedId() string {
	if m != nil {
		return m.BreedId
	}
	return ""
}

func (m *GetMovesForBreedRequest) GetVersionGroupId() VersionGroup {
	if m != nil {
		return m.VersionGroupId
	}
	return VersionGroup_UNKNOWN_VERSION_GROUP
}

type GetMovesForBreedResponse struct {
	BreedMoves           []*BreedMove `protobuf:"bytes,1,rep,name=breed_moves,json=breedMoves,proto3" json:"breed_moves,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMovesForBreedResponse) Reset()         { *m = GetMovesForBreedResponse{} }
func (m *GetMovesForBreedResponse) String() string { return proto.CompactTextString(m) }
func (*GetMovesForBreedResponse) ProtoMessage()    {}
func (*GetMovesForBreedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_239b4783ea3a6a28, []int{1}
}

func (m *GetMovesForBreedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovesForBreedResponse.Unmarshal(m, b)
}
func (m *GetMovesForBreedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovesForBreedResponse.Marshal(b, m, deterministic)
}
func (m *GetMovesForBreedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovesForBreedResponse.Merge(m, src)
}
func (m *GetMovesForBreedResponse) XXX_Size() int {
	return xxx_messageInfo_GetMovesForBreedResponse.Size(m)
}
func (m *GetMovesForBreedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovesForBreedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovesForBreedResponse proto.InternalMessageInfo

func (m *GetMovesForBreedResponse) GetBreedMoves() []*BreedMove {
	if m != nil {
		return m.BreedMoves
	}
	return nil
}

type BreedMove struct {
	BreedId              string       `protobuf:"bytes,1,opt,name=breed_id,json=breedId,proto3" json:"breed_id,omitempty"`
	VersionGroupId       VersionGroup `protobuf:"varint,2,opt,name=version_group_id,json=versionGroupId,proto3,enum=pokemon.VersionGroup" json:"version_group_id,omitempty"`
	MoveId               string       `protobuf:"bytes,3,opt,name=move_id,json=moveId,proto3" json:"move_id,omitempty"`
	LearnMethodId        LearnMethod  `protobuf:"varint,4,opt,name=learn_method_id,json=learnMethodId,proto3,enum=pokemon.LearnMethod" json:"learn_method_id,omitempty"`
	Level                int32        `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BreedMove) Reset()         { *m = BreedMove{} }
func (m *BreedMove) String() string { return proto.CompactTextString(m) }
func (*BreedMove) ProtoMessage()    {}
func (*BreedMove) Descriptor() ([]byte, []int) {
	return fileDescriptor_239b4783ea3a6a28, []int{2}
}

func (m *BreedMove) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BreedMove.Unmarshal(m, b)
}
func (m *BreedMove) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BreedMove.Marshal(b, m, deterministic)
}
func (m *BreedMove) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BreedMove.Merge(m, src)
}
func (m *BreedMove) XXX_Size() int {
	return xxx_messageInfo_BreedMove.Size(m)
}
func (m *BreedMove) XXX_DiscardUnknown() {
	xxx_messageInfo_BreedMove.DiscardUnknown(m)
}

var xxx_messageInfo_BreedMove proto.InternalMessageInfo

func (m *BreedMove) GetBreedId() string {
	if m != nil {
		return m.BreedId
	}
	return ""
}

func (m *BreedMove) GetVersionGroupId() VersionGroup {
	if m != nil {
		return m.VersionGroupId
	}
	return VersionGroup_UNKNOWN_VERSION_GROUP
}

func (m *BreedMove) GetMoveId() string {
	if m != nil {
		return m.MoveId
	}
	return ""
}

func (m *BreedMove) GetLearnMethodId() LearnMethod {
	if m != nil {
		return m.LearnMethodId
	}
	return LearnMethod_LEARN_METHOD_UNKNOWN
}

func (m *BreedMove) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func init() {
	proto.RegisterEnum("pokemon.LearnMethod", LearnMethod_name, LearnMethod_value)
	proto.RegisterType((*GetMovesForBreedRequest)(nil), "pokemon.GetMovesForBreedRequest")
	proto.RegisterType((*GetMovesForBreedResponse)(nil), "pokemon.GetMovesForBreedResponse")
	proto.RegisterType((*BreedMove)(nil), "pokemon.BreedMove")
}

func init() { proto.RegisterFile("pokemon/breedmove.proto", fileDescriptor_239b4783ea3a6a28) }

var fileDescriptor_239b4783ea3a6a28 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x8f, 0xd2, 0x4e,
	0x18, 0xc6, 0xb7, 0xcb, 0x42, 0xe9, 0xcb, 0x77, 0x61, 0xf2, 0x7e, 0x51, 0x10, 0x2f, 0xc8, 0x89,
	0x78, 0xc0, 0x84, 0xbd, 0x9a, 0x98, 0x02, 0xa5, 0x9d, 0x6c, 0x7f, 0x90, 0x69, 0xbb, 0xbb, 0x7a,
	0x99, 0x88, 0x9d, 0x28, 0x11, 0x18, 0x6c, 0xa1, 0x7f, 0xa9, 0x07, 0xff, 0x1c, 0x33, 0x05, 0xea,
	0xaa, 0xd1, 0x9b, 0xb7, 0x3e, 0x79, 0x9e, 0xf7, 0xf3, 0x4e, 0xdb, 0x67, 0xa0, 0xb3, 0x93, 0x9f,
	0xc5, 0x46, 0x6e, 0x5f, 0x2d, 0x53, 0x21, 0x92, 0x8d, 0xcc, 0xc5, 0x68, 0x97, 0xca, 0xbd, 0x44,
	0xfd, 0x64, 0xf4, 0x7a, 0xe7, 0x44, 0x2e, 0xd2, 0x6c, 0x25, 0xb7, 0x1f, 0x53, 0x79, 0xd8, 0x1d,
	0x43, 0x83, 0x03, 0x74, 0x6c, 0xb1, 0xf7, 0x64, 0x2e, 0xb2, 0xb9, 0x4c, 0x27, 0x0a, 0xc1, 0xc4,
	0x97, 0x83, 0xc8, 0xf6, 0xf8, 0x0c, 0xea, 0x05, 0x92, 0xaf, 0x92, 0xae, 0xd6, 0xd7, 0x86, 0x06,
	0xd3, 0x0b, 0x4d, 0x13, 0x7c, 0x03, 0xe4, 0xc4, 0xe2, 0x05, 0x4c, 0x45, 0x2e, 0xfb, 0xda, 0xb0,
	0x39, 0x7e, 0x32, 0x3a, 0x2d, 0x1b, 0xdd, 0x1d, 0x03, 0xb6, 0xf2, 0x59, 0x33, 0x7f, 0xa4, 0x68,
	0x32, 0x08, 0xa0, 0xfb, 0xfb, 0xda, 0x6c, 0x27, 0xb7, 0x99, 0xc0, 0x1b, 0x68, 0x1c, 0xf7, 0xaa,
	0x77, 0xc9, 0xba, 0x5a, 0xbf, 0x32, 0x6c, 0x8c, 0xb1, 0xe4, 0x16, 0x61, 0x35, 0xc9, 0x60, 0x79,
	0x7e, 0xcc, 0x06, 0x5f, 0x35, 0x30, 0x4a, 0xe7, 0x5f, 0x1e, 0x1d, 0x3b, 0xa0, 0xab, 0x83, 0xa9,
	0xb9, 0x4a, 0x81, 0xae, 0x29, 0x49, 0x13, 0x7c, 0x0d, 0xad, 0xb5, 0x78, 0x9f, 0x6e, 0xf9, 0x46,
	0xec, 0x3f, 0xc9, 0x62, 0xf7, 0x55, 0x01, 0x6e, 0x97, 0x60, 0x57, 0xf9, 0x5e, 0x61, 0xb3, 0xeb,
	0xf5, 0x0f, 0x41, 0x13, 0x6c, 0x43, 0x75, 0x2d, 0x72, 0xb1, 0xee, 0x56, 0xfb, 0xda, 0xb0, 0xca,
	0x8e, 0xe2, 0xe5, 0x37, 0x0d, 0x1a, 0x8f, 0x86, 0xb0, 0x0b, 0x6d, 0xd7, 0x32, 0x99, 0xcf, 0x3d,
	0x2b, 0x72, 0x82, 0x19, 0x8f, 0xfd, 0x5b, 0x3f, 0xb8, 0xf7, 0xc9, 0x05, 0xfe, 0x07, 0x75, 0xd7,
	0xba, 0xb3, 0x5c, 0x1e, 0x2f, 0x88, 0x86, 0x3a, 0x54, 0x2c, 0xdb, 0x26, 0x97, 0x68, 0x40, 0x35,
	0x8a, 0xa3, 0x80, 0x91, 0x0a, 0x36, 0x40, 0xf7, 0xcc, 0xa9, 0x43, 0x7d, 0x8b, 0x5c, 0xe1, 0x73,
	0xe8, 0x84, 0x91, 0x39, 0xa3, 0xb1, 0xc7, 0xc3, 0x98, 0xcd, 0xa9, 0x6f, 0xf3, 0x05, 0xbd, 0x35,
	0xa7, 0x4e, 0x4c, 0xaa, 0x88, 0xd0, 0x74, 0xa9, 0xed, 0x44, 0x7c, 0x62, 0xba, 0x2e, 0x57, 0xa0,
	0x1a, 0xf6, 0xe0, 0xe9, 0x34, 0x70, 0x83, 0x30, 0xb4, 0x62, 0x8f, 0x2f, 0x62, 0x46, 0xe7, 0x74,
	0x6a, 0x46, 0x34, 0xf0, 0x89, 0x8e, 0xd7, 0x60, 0x3c, 0xcc, 0x78, 0xe8, 0x98, 0xb3, 0xe0, 0x9e,
	0xd4, 0xf1, 0x7f, 0x68, 0x3d, 0xcc, 0x7e, 0xce, 0x18, 0xd8, 0x82, 0xc6, 0x3c, 0x60, 0x1e, 0x9f,
	0x3a, 0xa6, 0x6f, 0x5b, 0x04, 0xc6, 0x1b, 0x20, 0xe5, 0x0f, 0x0b, 0x45, 0x9a, 0xaf, 0x3e, 0x08,
	0x7c, 0x0b, 0xe4, 0xd7, 0x5a, 0x60, 0xbf, 0xfc, 0x7a, 0x7f, 0x28, 0x6a, 0xef, 0xc5, 0x5f, 0x12,
	0xc7, 0x4e, 0x0d, 0x2e, 0x26, 0xc6, 0xbb, 0xf3, 0x7d, 0x58, 0xd6, 0x8a, 0xea, 0xdf, 0x7c, 0x0f,
	0x00, 0x00, 0xff, 0xff, 0xfb, 0x34, 0x3f, 0xe2, 0x3a, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BreedMoveServiceClient is the client API for BreedMoveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BreedMoveServiceClient interface {
	GetMovesForBreed(ctx context.Context, in *GetMovesForBreedRequest, opts ...grpc.CallOption) (*GetMovesForBreedResponse, error)
}

type breedMoveServiceClient struct {
	cc *grpc.ClientConn
}

func NewBreedMoveServiceClient(cc *grpc.ClientConn) BreedMoveServiceClient {
	return &breedMoveServiceClient{cc}
}

func (c *breedMoveServiceClient) GetMovesForBreed(ctx context.Context, in *GetMovesForBreedRequest, opts ...grpc.CallOption) (*GetMovesForBreedResponse, error) {
	out := new(GetMovesForBreedResponse)
	err := c.cc.Invoke(ctx, "/pokemon.BreedMoveService/GetMovesForBreed", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BreedMoveServiceServer is the server API for BreedMoveService service.
type BreedMoveServiceServer interface {
	GetMovesForBreed(context.Context, *GetMovesForBreedRequest) (*GetMovesForBreedResponse, error)
}

// UnimplementedBreedMoveServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBreedMoveServiceServer struct {
}

func (*UnimplementedBreedMoveServiceServer) GetMovesForBreed(ctx context.Context, req *GetMovesForBreedRequest) (*GetMovesForBreedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMovesForBreed not implemented")
}

func RegisterBreedMoveServiceServer(s *grpc.Server, srv BreedMoveServiceServer) {
	s.RegisterService(&_BreedMoveService_serviceDesc, srv)
}

func _BreedMoveService_GetMovesForBreed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMovesForBreedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BreedMoveServiceServer).GetMovesForBreed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokemon.BreedMoveService/GetMovesForBreed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BreedMoveServiceServer).GetMovesForBreed(ctx, req.(*GetMovesForBreedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BreedMoveService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon.BreedMoveService",
	HandlerType: (*BreedMoveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMovesForBreed",
			Handler:    _BreedMoveService_GetMovesForBreed_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pokemon/breedmove.proto",
}
