// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pokemon/pokemon.proto

package pokemon

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Pokemon struct {
	// @inject_tag: sql:",pk"
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" sql:",pk"`
	// @inject_tag: sql:",notnull"
	BreedId int32 `protobuf:"varint,2,opt,name=breed_id,json=breedId,proto3" json:"breed_id,omitempty" sql:",notnull"`
	// @inject_tag: sql:"-"
	BreedSummary         *BreedSummary `protobuf:"bytes,3,opt,name=breed_summary,json=breedSummary,proto3" json:"breed_summary,omitempty" sql:"-"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Pokemon) Reset()         { *m = Pokemon{} }
func (m *Pokemon) String() string { return proto.CompactTextString(m) }
func (*Pokemon) ProtoMessage()    {}
func (*Pokemon) Descriptor() ([]byte, []int) {
	return fileDescriptor_27fc31544a7745c3, []int{0}
}

func (m *Pokemon) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pokemon.Unmarshal(m, b)
}
func (m *Pokemon) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pokemon.Marshal(b, m, deterministic)
}
func (m *Pokemon) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pokemon.Merge(m, src)
}
func (m *Pokemon) XXX_Size() int {
	return xxx_messageInfo_Pokemon.Size(m)
}
func (m *Pokemon) XXX_DiscardUnknown() {
	xxx_messageInfo_Pokemon.DiscardUnknown(m)
}

var xxx_messageInfo_Pokemon proto.InternalMessageInfo

func (m *Pokemon) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Pokemon) GetBreedId() int32 {
	if m != nil {
		return m.BreedId
	}
	return 0
}

func (m *Pokemon) GetBreedSummary() *BreedSummary {
	if m != nil {
		return m.BreedSummary
	}
	return nil
}

type GetPokemonRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPokemonRequest) Reset()         { *m = GetPokemonRequest{} }
func (m *GetPokemonRequest) String() string { return proto.CompactTextString(m) }
func (*GetPokemonRequest) ProtoMessage()    {}
func (*GetPokemonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27fc31544a7745c3, []int{1}
}

func (m *GetPokemonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPokemonRequest.Unmarshal(m, b)
}
func (m *GetPokemonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPokemonRequest.Marshal(b, m, deterministic)
}
func (m *GetPokemonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPokemonRequest.Merge(m, src)
}
func (m *GetPokemonRequest) XXX_Size() int {
	return xxx_messageInfo_GetPokemonRequest.Size(m)
}
func (m *GetPokemonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPokemonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPokemonRequest proto.InternalMessageInfo

func (m *GetPokemonRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetPokemonResponse struct {
	Pokemon              *Pokemon `protobuf:"bytes,1,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPokemonResponse) Reset()         { *m = GetPokemonResponse{} }
func (m *GetPokemonResponse) String() string { return proto.CompactTextString(m) }
func (*GetPokemonResponse) ProtoMessage()    {}
func (*GetPokemonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27fc31544a7745c3, []int{2}
}

func (m *GetPokemonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPokemonResponse.Unmarshal(m, b)
}
func (m *GetPokemonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPokemonResponse.Marshal(b, m, deterministic)
}
func (m *GetPokemonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPokemonResponse.Merge(m, src)
}
func (m *GetPokemonResponse) XXX_Size() int {
	return xxx_messageInfo_GetPokemonResponse.Size(m)
}
func (m *GetPokemonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPokemonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPokemonResponse proto.InternalMessageInfo

func (m *GetPokemonResponse) GetPokemon() *Pokemon {
	if m != nil {
		return m.Pokemon
	}
	return nil
}

type ListPokemonRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListPokemonRequest) Reset()         { *m = ListPokemonRequest{} }
func (m *ListPokemonRequest) String() string { return proto.CompactTextString(m) }
func (*ListPokemonRequest) ProtoMessage()    {}
func (*ListPokemonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27fc31544a7745c3, []int{3}
}

func (m *ListPokemonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPokemonRequest.Unmarshal(m, b)
}
func (m *ListPokemonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPokemonRequest.Marshal(b, m, deterministic)
}
func (m *ListPokemonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPokemonRequest.Merge(m, src)
}
func (m *ListPokemonRequest) XXX_Size() int {
	return xxx_messageInfo_ListPokemonRequest.Size(m)
}
func (m *ListPokemonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPokemonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListPokemonRequest proto.InternalMessageInfo

type ListPokemonResponse struct {
	Pokemon              []*Pokemon `protobuf:"bytes,1,rep,name=pokemon,proto3" json:"pokemon,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListPokemonResponse) Reset()         { *m = ListPokemonResponse{} }
func (m *ListPokemonResponse) String() string { return proto.CompactTextString(m) }
func (*ListPokemonResponse) ProtoMessage()    {}
func (*ListPokemonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27fc31544a7745c3, []int{4}
}

func (m *ListPokemonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListPokemonResponse.Unmarshal(m, b)
}
func (m *ListPokemonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListPokemonResponse.Marshal(b, m, deterministic)
}
func (m *ListPokemonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListPokemonResponse.Merge(m, src)
}
func (m *ListPokemonResponse) XXX_Size() int {
	return xxx_messageInfo_ListPokemonResponse.Size(m)
}
func (m *ListPokemonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListPokemonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListPokemonResponse proto.InternalMessageInfo

func (m *ListPokemonResponse) GetPokemon() []*Pokemon {
	if m != nil {
		return m.Pokemon
	}
	return nil
}

type InternalCreatePokemonRequest struct {
	BreedId                  string   `protobuf:"bytes,1,opt,name=breed_id,json=breedId,proto3" json:"breed_id,omitempty"`
	Level                    int32    `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	OverrideGenderIsMale     bool     `protobuf:"varint,3,opt,name=override_gender_is_male,json=overrideGenderIsMale,proto3" json:"override_gender_is_male,omitempty"`
	OverrideIvHp             int32    `protobuf:"varint,4,opt,name=override_iv_hp,json=overrideIvHp,proto3" json:"override_iv_hp,omitempty"`
	OverrideIvAttack         int32    `protobuf:"varint,5,opt,name=override_iv_attack,json=overrideIvAttack,proto3" json:"override_iv_attack,omitempty"`
	OverrideIvDefense        int32    `protobuf:"varint,6,opt,name=override_iv_defense,json=overrideIvDefense,proto3" json:"override_iv_defense,omitempty"`
	OverrideIvSpecialAttack  int32    `protobuf:"varint,7,opt,name=override_iv_special_attack,json=overrideIvSpecialAttack,proto3" json:"override_iv_special_attack,omitempty"`
	OverrideIvSpecialDefense int32    `protobuf:"varint,8,opt,name=override_iv_special_defense,json=overrideIvSpecialDefense,proto3" json:"override_iv_special_defense,omitempty"`
	OverrideIvSpecialSpeed   int32    `protobuf:"varint,9,opt,name=override_iv_special_speed,json=overrideIvSpecialSpeed,proto3" json:"override_iv_special_speed,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *InternalCreatePokemonRequest) Reset()         { *m = InternalCreatePokemonRequest{} }
func (m *InternalCreatePokemonRequest) String() string { return proto.CompactTextString(m) }
func (*InternalCreatePokemonRequest) ProtoMessage()    {}
func (*InternalCreatePokemonRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_27fc31544a7745c3, []int{5}
}

func (m *InternalCreatePokemonRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalCreatePokemonRequest.Unmarshal(m, b)
}
func (m *InternalCreatePokemonRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalCreatePokemonRequest.Marshal(b, m, deterministic)
}
func (m *InternalCreatePokemonRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalCreatePokemonRequest.Merge(m, src)
}
func (m *InternalCreatePokemonRequest) XXX_Size() int {
	return xxx_messageInfo_InternalCreatePokemonRequest.Size(m)
}
func (m *InternalCreatePokemonRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalCreatePokemonRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InternalCreatePokemonRequest proto.InternalMessageInfo

func (m *InternalCreatePokemonRequest) GetBreedId() string {
	if m != nil {
		return m.BreedId
	}
	return ""
}

func (m *InternalCreatePokemonRequest) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *InternalCreatePokemonRequest) GetOverrideGenderIsMale() bool {
	if m != nil {
		return m.OverrideGenderIsMale
	}
	return false
}

func (m *InternalCreatePokemonRequest) GetOverrideIvHp() int32 {
	if m != nil {
		return m.OverrideIvHp
	}
	return 0
}

func (m *InternalCreatePokemonRequest) GetOverrideIvAttack() int32 {
	if m != nil {
		return m.OverrideIvAttack
	}
	return 0
}

func (m *InternalCreatePokemonRequest) GetOverrideIvDefense() int32 {
	if m != nil {
		return m.OverrideIvDefense
	}
	return 0
}

func (m *InternalCreatePokemonRequest) GetOverrideIvSpecialAttack() int32 {
	if m != nil {
		return m.OverrideIvSpecialAttack
	}
	return 0
}

func (m *InternalCreatePokemonRequest) GetOverrideIvSpecialDefense() int32 {
	if m != nil {
		return m.OverrideIvSpecialDefense
	}
	return 0
}

func (m *InternalCreatePokemonRequest) GetOverrideIvSpecialSpeed() int32 {
	if m != nil {
		return m.OverrideIvSpecialSpeed
	}
	return 0
}

type InternalCreatePokemonResponse struct {
	Pokemon              *Pokemon `protobuf:"bytes,1,opt,name=pokemon,proto3" json:"pokemon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalCreatePokemonResponse) Reset()         { *m = InternalCreatePokemonResponse{} }
func (m *InternalCreatePokemonResponse) String() string { return proto.CompactTextString(m) }
func (*InternalCreatePokemonResponse) ProtoMessage()    {}
func (*InternalCreatePokemonResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_27fc31544a7745c3, []int{6}
}

func (m *InternalCreatePokemonResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalCreatePokemonResponse.Unmarshal(m, b)
}
func (m *InternalCreatePokemonResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalCreatePokemonResponse.Marshal(b, m, deterministic)
}
func (m *InternalCreatePokemonResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalCreatePokemonResponse.Merge(m, src)
}
func (m *InternalCreatePokemonResponse) XXX_Size() int {
	return xxx_messageInfo_InternalCreatePokemonResponse.Size(m)
}
func (m *InternalCreatePokemonResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalCreatePokemonResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InternalCreatePokemonResponse proto.InternalMessageInfo

func (m *InternalCreatePokemonResponse) GetPokemon() *Pokemon {
	if m != nil {
		return m.Pokemon
	}
	return nil
}

func init() {
	proto.RegisterType((*Pokemon)(nil), "pokemon.Pokemon")
	proto.RegisterType((*GetPokemonRequest)(nil), "pokemon.GetPokemonRequest")
	proto.RegisterType((*GetPokemonResponse)(nil), "pokemon.GetPokemonResponse")
	proto.RegisterType((*ListPokemonRequest)(nil), "pokemon.ListPokemonRequest")
	proto.RegisterType((*ListPokemonResponse)(nil), "pokemon.ListPokemonResponse")
	proto.RegisterType((*InternalCreatePokemonRequest)(nil), "pokemon.InternalCreatePokemonRequest")
	proto.RegisterType((*InternalCreatePokemonResponse)(nil), "pokemon.InternalCreatePokemonResponse")
}

func init() { proto.RegisterFile("pokemon/pokemon.proto", fileDescriptor_27fc31544a7745c3) }

var fileDescriptor_27fc31544a7745c3 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0x5f, 0x8b, 0xd3, 0x4c,
	0x14, 0xc6, 0x49, 0xfb, 0x76, 0xdb, 0x9e, 0xee, 0x96, 0xee, 0x69, 0xfb, 0x6e, 0x9a, 0xad, 0x58,
	0xe2, 0x1f, 0xca, 0x22, 0x0d, 0x56, 0xbc, 0x70, 0x45, 0x70, 0x57, 0x61, 0x2d, 0x2a, 0x48, 0x7b,
	0x27, 0x48, 0x98, 0x36, 0xc7, 0x3a, 0x6c, 0x9a, 0xc4, 0x4c, 0x36, 0x20, 0xe2, 0x8d, 0x37, 0x7e,
	0x00, 0x3f, 0x91, 0x9f, 0xc1, 0x3b, 0xaf, 0xfd, 0x20, 0xb2, 0x93, 0x4c, 0x13, 0xdb, 0xb8, 0xe2,
	0xd5, 0x32, 0xe7, 0xf9, 0x3d, 0xe7, 0x99, 0x39, 0x7b, 0x52, 0xe8, 0x06, 0xfe, 0x39, 0xad, 0x7c,
	0xcf, 0x4a, 0xff, 0x8e, 0x82, 0xd0, 0x8f, 0x7c, 0xac, 0xa6, 0x47, 0xa3, 0xbf, 0xf4, 0xfd, 0xa5,
	0x4b, 0x16, 0x0b, 0xb8, 0xc5, 0x3c, 0xcf, 0x8f, 0x58, 0xc4, 0x7d, 0x4f, 0x24, 0x98, 0xd1, 0x56,
	0xee, 0x79, 0x48, 0xe4, 0x24, 0x45, 0x33, 0x80, 0xea, 0xab, 0xa4, 0x8c, 0x4d, 0x28, 0x71, 0x47,
	0xd7, 0x06, 0xda, 0xb0, 0x3e, 0x2d, 0x71, 0x07, 0x7b, 0x50, 0x93, 0xa4, 0xcd, 0x1d, 0xbd, 0x34,
	0xd0, 0x86, 0x95, 0x69, 0x55, 0x9e, 0x27, 0x0e, 0x1e, 0xc3, 0x5e, 0x22, 0x89, 0x8b, 0xd5, 0x8a,
	0x85, 0x1f, 0xf4, 0xf2, 0x40, 0x1b, 0x36, 0xc6, 0xdd, 0x91, 0xba, 0xd8, 0xe9, 0xa5, 0x3a, 0x4b,
	0xc4, 0xe9, 0xee, 0x3c, 0x77, 0x32, 0x6f, 0xc0, 0xfe, 0x19, 0x45, 0x69, 0xe8, 0x94, 0xde, 0x5f,
	0x90, 0x88, 0x36, 0xb3, 0xcd, 0xc7, 0x80, 0x79, 0x48, 0x04, 0xbe, 0x27, 0x08, 0x8f, 0x40, 0x3d,
	0x55, 0xa2, 0x8d, 0x71, 0x6b, 0x1d, 0xa8, 0x50, 0x05, 0x98, 0x1d, 0xc0, 0x17, 0x5c, 0x6c, 0xe4,
	0x98, 0x27, 0xd0, 0xfe, 0xad, 0x5a, 0xd4, 0xb8, 0x7c, 0x75, 0xe3, 0x6f, 0x65, 0xe8, 0x4f, 0xbc,
	0x88, 0x42, 0x8f, 0xb9, 0x4f, 0x42, 0x62, 0x11, 0x6d, 0xbc, 0x25, 0x3f, 0xb7, 0xe4, 0x45, 0xeb,
	0xb9, 0x75, 0xa0, 0xe2, 0x52, 0x4c, 0x6e, 0x3a, 0xcf, 0xe4, 0x80, 0xf7, 0xe1, 0xc0, 0x8f, 0x29,
	0x0c, 0xb9, 0x43, 0xf6, 0x92, 0x3c, 0x87, 0x42, 0x9b, 0x0b, 0x7b, 0xc5, 0x5c, 0x92, 0x73, 0xad,
	0x4d, 0x3b, 0x4a, 0x3e, 0x93, 0xea, 0x44, 0xbc, 0x64, 0x2e, 0xe1, 0x4d, 0x68, 0xae, 0x6d, 0x3c,
	0xb6, 0xdf, 0x05, 0xfa, 0x7f, 0xb2, 0xeb, 0xae, 0xaa, 0x4e, 0xe2, 0x67, 0x01, 0xde, 0x01, 0xcc,
	0x53, 0x2c, 0x8a, 0xd8, 0xe2, 0x5c, 0xaf, 0x48, 0xb2, 0x95, 0x91, 0x27, 0xb2, 0x8e, 0x23, 0x68,
	0xe7, 0x69, 0x87, 0xde, 0x92, 0x27, 0x48, 0xdf, 0x91, 0xf8, 0x7e, 0x86, 0x3f, 0x4d, 0x04, 0x7c,
	0x08, 0x46, 0x9e, 0x17, 0x01, 0x2d, 0x38, 0x73, 0x55, 0x4a, 0x55, 0xda, 0x0e, 0x32, 0xdb, 0x2c,
	0xd1, 0xd3, 0xb0, 0x47, 0x70, 0x58, 0x64, 0x56, 0xa1, 0x35, 0xe9, 0xd6, 0xb7, 0xdc, 0x2a, 0xfb,
	0x01, 0xf4, 0x8a, 0xec, 0x22, 0x20, 0x72, 0xf4, 0xba, 0x34, 0xff, 0xbf, 0x65, 0x9e, 0x5d, 0xaa,
	0xe6, 0x73, 0xb8, 0xf6, 0x87, 0x7f, 0xe1, 0xbf, 0x6f, 0xda, 0xf8, 0x47, 0x09, 0x9a, 0x69, 0x71,
	0x46, 0x61, 0xcc, 0x17, 0x84, 0x36, 0x40, 0xb6, 0xbe, 0x68, 0xac, 0xbd, 0x5b, 0x8b, 0x6f, 0x1c,
	0x16, 0x6a, 0xc9, 0x2d, 0x4c, 0xfd, 0xf3, 0xf7, 0x9f, 0x5f, 0x4b, 0x88, 0x2d, 0x2b, 0xbe, 0xab,
	0xbe, 0x79, 0xeb, 0x23, 0x77, 0x3e, 0xe1, 0x1b, 0x68, 0xe4, 0xf6, 0x18, 0xb3, 0x2e, 0xdb, 0x3b,
	0x6f, 0xf4, 0x8b, 0xc5, 0x34, 0xa3, 0x2d, 0x33, 0xf6, 0xb0, 0x91, 0xcb, 0xc0, 0x2f, 0x1a, 0x74,
	0x0b, 0x07, 0x84, 0xb7, 0xd6, 0xcd, 0xae, 0xfa, 0x06, 0x8c, 0xdb, 0x7f, 0xc3, 0xd2, 0xf4, 0xeb,
	0x32, 0xbd, 0x67, 0x76, 0x2c, 0x9e, 0x72, 0xb9, 0x6b, 0x1c, 0x6b, 0x47, 0xa7, 0xf5, 0xd7, 0x6a,
	0xce, 0xf3, 0x1d, 0xf9, 0x8b, 0x75, 0xef, 0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xe2, 0x1f,
	0x01, 0x06, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PokemonServiceClient is the client API for PokemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PokemonServiceClient interface {
	GetPokemon(ctx context.Context, in *GetPokemonRequest, opts ...grpc.CallOption) (*GetPokemonResponse, error)
	ListPokemon(ctx context.Context, in *ListPokemonRequest, opts ...grpc.CallOption) (*ListPokemonResponse, error)
	InternalCreatePokemon(ctx context.Context, in *InternalCreatePokemonRequest, opts ...grpc.CallOption) (*InternalCreatePokemonResponse, error)
}

type pokemonServiceClient struct {
	cc *grpc.ClientConn
}

func NewPokemonServiceClient(cc *grpc.ClientConn) PokemonServiceClient {
	return &pokemonServiceClient{cc}
}

func (c *pokemonServiceClient) GetPokemon(ctx context.Context, in *GetPokemonRequest, opts ...grpc.CallOption) (*GetPokemonResponse, error) {
	out := new(GetPokemonResponse)
	err := c.cc.Invoke(ctx, "/pokemon.PokemonService/GetPokemon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokemonServiceClient) ListPokemon(ctx context.Context, in *ListPokemonRequest, opts ...grpc.CallOption) (*ListPokemonResponse, error) {
	out := new(ListPokemonResponse)
	err := c.cc.Invoke(ctx, "/pokemon.PokemonService/ListPokemon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pokemonServiceClient) InternalCreatePokemon(ctx context.Context, in *InternalCreatePokemonRequest, opts ...grpc.CallOption) (*InternalCreatePokemonResponse, error) {
	out := new(InternalCreatePokemonResponse)
	err := c.cc.Invoke(ctx, "/pokemon.PokemonService/InternalCreatePokemon", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PokemonServiceServer is the server API for PokemonService service.
type PokemonServiceServer interface {
	GetPokemon(context.Context, *GetPokemonRequest) (*GetPokemonResponse, error)
	ListPokemon(context.Context, *ListPokemonRequest) (*ListPokemonResponse, error)
	InternalCreatePokemon(context.Context, *InternalCreatePokemonRequest) (*InternalCreatePokemonResponse, error)
}

// UnimplementedPokemonServiceServer can be embedded to have forward compatible implementations.
type UnimplementedPokemonServiceServer struct {
}

func (*UnimplementedPokemonServiceServer) GetPokemon(ctx context.Context, req *GetPokemonRequest) (*GetPokemonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPokemon not implemented")
}
func (*UnimplementedPokemonServiceServer) ListPokemon(ctx context.Context, req *ListPokemonRequest) (*ListPokemonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPokemon not implemented")
}
func (*UnimplementedPokemonServiceServer) InternalCreatePokemon(ctx context.Context, req *InternalCreatePokemonRequest) (*InternalCreatePokemonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InternalCreatePokemon not implemented")
}

func RegisterPokemonServiceServer(s *grpc.Server, srv PokemonServiceServer) {
	s.RegisterService(&_PokemonService_serviceDesc, srv)
}

func _PokemonService_GetPokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPokemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServiceServer).GetPokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokemon.PokemonService/GetPokemon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServiceServer).GetPokemon(ctx, req.(*GetPokemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokemonService_ListPokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPokemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServiceServer).ListPokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokemon.PokemonService/ListPokemon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServiceServer).ListPokemon(ctx, req.(*ListPokemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PokemonService_InternalCreatePokemon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InternalCreatePokemonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PokemonServiceServer).InternalCreatePokemon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pokemon.PokemonService/InternalCreatePokemon",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PokemonServiceServer).InternalCreatePokemon(ctx, req.(*InternalCreatePokemonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PokemonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pokemon.PokemonService",
	HandlerType: (*PokemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPokemon",
			Handler:    _PokemonService_GetPokemon_Handler,
		},
		{
			MethodName: "ListPokemon",
			Handler:    _PokemonService_ListPokemon_Handler,
		},
		{
			MethodName: "InternalCreatePokemon",
			Handler:    _PokemonService_InternalCreatePokemon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pokemon/pokemon.proto",
}
