settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: pokemon-service
  path: .
  commands:
    vet:
      status: true
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
